from __future__ import annotations

from typing import Any, Callable, Generic, Optional, Protocol, Sequence, Tuple, TypeVar

_T = TypeVar("_T")


class _Widget:
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...
    def bind(self, sequence: Any = ..., command: Any = ..., add: bool = ...) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def destroy(self) -> None: ...
    def focus_set(self) -> None: ...
    def winfo_toplevel(self) -> Any: ...


class CTk(_Widget):
    def title(self, title: str) -> None: ...
    def geometry(self, geometry_string: str) -> None: ...
    def minsize(self, width: int, height: int) -> None: ...
    def protocol(self, name: str, func: Any) -> None: ...
    def wait_window(self, window: Any = ...) -> None: ...
    def mainloop(self, *args: Any, **kwargs: Any) -> None: ...
    def after(self, ms: int, func: Any, *args: Any) -> Any: ...
    def after_cancel(self, id: Any) -> None: ...
    def bind_all(self, sequence: Any, func: Any) -> None: ...
    def clipboard_clear(self) -> None: ...
    def clipboard_append(self, text: str) -> None: ...
    def focus_get(self) -> Any: ...
    def destroy(self) -> None: ...
    def grid_columnconfigure(self, index: Any, weight: int = ..., minsize: int = ...) -> None: ...
    def grid_rowconfigure(self, index: Any, weight: int = ..., minsize: int = ...) -> None: ...


class CTkToplevel(_Widget):
    def transient(self, master: Any) -> None: ...
    def grab_set(self) -> None: ...
    def wait_window(self, window: Any = ...) -> None: ...
    def update_idletasks(self) -> None: ...
    def winfo_screenwidth(self) -> int: ...
    def winfo_screenheight(self) -> int: ...
    def protocol(self, name: str, func: Any) -> None: ...
    def resizable(self, width: bool, height: bool) -> None: ...
    def title(self, title: str) -> None: ...
    def geometry(self, geometry_string: str) -> None: ...


class CTkFrame(_Widget):
    def grid_propagate(self, flag: bool) -> None: ...
    def grid_columnconfigure(self, index: Any, weight: int = ..., minsize: int = ...) -> None: ...
    def grid_rowconfigure(self, index: Any, weight: int = ..., minsize: int = ...) -> None: ...


class CTkScrollableFrame(CTkFrame):
    ...


class CTkLabel(_Widget):
    ...


class CTkButton(_Widget):
    ...


class CTkEntry(_Widget):
    def delete(self, first_index: Any, last_index: Any = ...) -> None: ...
    def insert(self, index: Any, string: str) -> None: ...
    def get(self) -> str: ...
    def select_range(self, start_index: Any, end_index: Any) -> None: ...


class CTkTextbox(_Widget):
    def delete(self, index1: Any, index2: Any = ...) -> None: ...
    def insert(self, index: Any, text: str) -> None: ...
    def get(self, index1: Any, index2: Any = ...) -> str: ...


class CTkOptionMenu(_Widget):
    ...


class CTkFont:
    def __init__(self, family: str = ..., size: int = ..., weight: str = ..., **kwargs: Any) -> None: ...


class StringVar(Generic[_T]):
    def __init__(self, value: Any = ...) -> None: ...
    def get(self) -> Any: ...
    def set(self, value: Any) -> None: ...


def set_appearance_mode(mode_string: str) -> None: ...
def set_default_color_theme(color_string: str) -> None: ...
